name: mycall
description: Личный мессенджер с видеозвонками на своей инфраструктуре.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_webrtc: ^0.12.5        # WebRTC: камера, микрофон, P2P-медиа
  shared_preferences: ^2.3.2     # хранение адреса сервера и токена
  flutter_local_notifications: ^17.2.3  # уведомление о входящем звонке
  wakelock_plus: ^1.2.8          # не гасить экран во время звонка
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
